networks:
  weatherarchive-network:
    driver: bridge

services:
  weatherarchive:
    build:
      context: .
      dockerfile: WeatherArchive/Dockerfile
    image: weatherarchive
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=leplik8346
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - COMPOSE_BAKE=true
    ports:
      - "5279:80"
      - "5278:443"
    networks:
      - weatherarchive-network
    depends_on:
      - postgres
    volumes:
      - ~/.aspnet/https:/https:ro

  postgres:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=weather_archive
    networks:
      - weatherarchive-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: